# fly.toml app configuration file generated for whisper-bot on 2024-04-06T16:29:49-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whisper-bot'
primary_region = 'lax'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
